//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarządzanieBudżetem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudżetEntities : DbContext
    {
        public BudżetEntities()
            : base("name=BudżetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Faktury> Faktury { get; set; }
        public virtual DbSet<Projekty> Projekty { get; set; }
        public virtual DbSet<Użytkownicy> Użytkownicy { get; set; }
        public virtual DbSet<Wnioski> Wnioski { get; set; }
        public virtual DbSet<Zadania> Zadania { get; set; }
    }
}
