//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarządzanieBudżetem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury
    {
        public int IdFaktury { get; set; }
        public string Nr_faktury { get; set; }
        public Nullable<decimal> Kwota { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> Data_Faktury { get; set; }
        public string Jednostka { get; set; }
        public string Budynek { get; set; }
        public string Pokój { get; set; }
        public Nullable<int> IdZadania { get; set; }
    
        public virtual Zadania Zadania { get; set; }
    }
}
