//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarządzanieBudżetem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projekty()
        {
            this.Zadania = new HashSet<Zadania>();
        }
    
        public int IdProjektu { get; set; }
        public string Nazwa { get; set; }
        public System.DateTime Data_Utworzenia { get; set; }
        public System.DateTime Ostatnie_Użycie { get; set; }
        public int LpColumn { get; set; }
        public int NazwaKosztuColumn { get; set; }
        public int WartoscOgolnaColumn { get; set; }
        public int WydatkiKwalifikowaneColumn { get; set; }
        public int DofinansowanieColumn { get; set; }
        public int KategoriaKosztowColumn { get; set; }
        public Nullable<int> IdUżytkownika { get; set; }
    
        public virtual Użytkownicy Użytkownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadania> Zadania { get; set; }
    }
}
