//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarządzanieBudżetem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wnioski
    {
        public int IdWniosku { get; set; }
        public string NrKsięgowy { get; set; }
        public Nullable<System.DateTime> Data_Wniosku { get; set; }
        public Nullable<decimal> Kwota_Dofinansowania { get; set; }
        public Nullable<int> IdZadania { get; set; }
    
        public virtual Zadania Zadania { get; set; }
    }
}
