CREATE TABLE U¿ytkownicy (
    IdU¿ytkownika INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(50) NOT NULL,
    Has³o NVARCHAR(100) NOT NULL,
    Sól NVARCHAR(50) NOT NULL,
    Rola NVARCHAR(50) NOT NULL
);
